import { describe, expect, test } from 'vitest';

import { codes, typecheck } from './test-tsc.ts';

// Pins TypeScript resolution behaviour the handbook does not contract; the sidecar scheme rests on it.

type Mode = 'bundler' | 'nodenext';

interface Layout {
  mode: Mode;
  index: string;
  sidecar?: boolean;
  fallback?: boolean;
  lib?: string[];
}

const SIDECAR = `// @generated by slang-loader — do not edit.
declare const code: string;
export default code;
export const entryPoints: [{ name: 'computeMain'; stage: 'compute'; workgroupSize: null }];
export const reflection: unknown;
`;

const INDEX = `export interface SlangEntryPoint {
  name: string;
  stage: string;
  workgroupSize: [number, number, number] | null;
}
`;

const MODULE = `declare const code: string;
export default code;
export const entryPoints: import('slang-loader').SlangEntryPoint[];
export const reflection: unknown;
`;

const FALLBACK = `declare module '*.slang' {
  export { default } from 'slang-loader/module';
  export * from 'slang-loader/module';
}

declare module '*.slang?worker' {
  export { default } from 'slang-loader/module';
}
`;

const MODULES: Record<Mode, { module: string; resolution: string; type: string }> = {
  bundler: { module: 'preserve', resolution: 'bundler', type: 'module' },
  nodenext: { module: 'nodenext', resolution: 'nodenext', type: 'module' },
};

function project({ mode, index, sidecar = false, fallback = false, lib }: Layout): Record<string, string> {
  const { module, resolution, type } = MODULES[mode];

  const files: Record<string, string> = {
    'package.json': JSON.stringify({ name: 'consumer', private: true, type }),
    'tsconfig.json': JSON.stringify({
      compilerOptions: {
        noEmit: true,
        strict: true,
        skipLibCheck: false,
        module,
        moduleResolution: resolution,
        types: [],
        ...(lib ? { lib } : {}),
      },
    }),
    'index.ts': index,
    'scene.slang': '[shader("compute")] void computeMain() {}',
    'node_modules/slang-loader/package.json': JSON.stringify({
      name: 'slang-loader',
      version: '0.0.0',
      type: 'module',
      types: './dist/index.d.mts',
      exports: {
        '.': { types: './dist/index.d.mts', default: './dist/index.mjs' },
        './module': { types: './src/module.d.ts' },
      },
    }),
    'node_modules/slang-loader/src/module.d.ts': MODULE,
    'node_modules/slang-loader/dist/index.d.mts': INDEX,
  };

  if (sidecar) files['scene.slang.d.ts'] = SIDECAR;
  if (fallback) files['typings.d.ts'] = FALLBACK;

  return files;
}

const LITERAL = `import code, { entryPoints } from './scene.slang';\nconst name: 'computeMain' = entryPoints[0].name;\n`;
const WIDENED = `import code, { entryPoints } from './scene.slang';\nconst name: string = entryPoints[0].name;\n`;
const WRONG = `import code, { entryPoints } from './scene.slang';\nconst name: 'nope' = entryPoints[0].name;\n`;

describe('the harness itself reports what it should', () => {
  test('a deliberate type error is seen, so a clean run means something', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', sidecar: true, index: WRONG }));

    expect(codes(diagnostics)).toContain('TS2322');
  });
});

describe('sidecar resolution', () => {
  test('bundler resolves the sidecar and keeps entry point names literal', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', sidecar: true, index: LITERAL }));

    expect(diagnostics).toEqual([]);
  });

  test('nodenext does not resolve the sidecar and falls back to the ambient pattern', () => {
    const diagnostics = typecheck(project({ mode: 'nodenext', sidecar: true, fallback: true, index: WIDENED }));

    expect(diagnostics).toEqual([]);
  });

  test('nodenext therefore loses the literal names', () => {
    const diagnostics = typecheck(project({ mode: 'nodenext', sidecar: true, fallback: true, index: LITERAL }));

    expect(codes(diagnostics)).toContain('TS2322');
  });
});

describe('the consumer-owned ambient fallback', () => {
  test('covers a shader whose sidecar has not been generated yet', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', fallback: true, index: WIDENED }));

    expect(diagnostics).toEqual([]);
  });

  test('is required — without it an ungenerated shader does not resolve at all', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', index: WIDENED }));

    expect(codes(diagnostics)).toContain('TS2307');
  });

  test('loses to the sidecar when both are present', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', sidecar: true, fallback: true, index: LITERAL }));

    expect(diagnostics).toEqual([]);
  });

  test('does not drag in DOM types, so a non-browser project can load it', () => {
    const diagnostics = typecheck(project({ mode: 'bundler', fallback: true, lib: ['ESNext'], index: WIDENED }));

    expect(diagnostics).toEqual([]);
  });

  test('does not describe raw imports that bypass the plugin', () => {
    const index = `import raw from './scene.slang?raw';\nconst code: string = raw;\n`;
    const diagnostics = typecheck(project({ mode: 'bundler', sidecar: true, fallback: true, index }));

    expect(codes(diagnostics)).toContain('TS2307');
  });

  test('covers worker queries without requiring DOM types', () => {
    const index = `import worker from './scene.slang?worker';\nconst code: string = worker;\n`;
    const diagnostics = typecheck(project({ mode: 'bundler', fallback: true, lib: ['ESNext'], index }));

    expect(diagnostics).toEqual([]);
  });
});
