import type { SlangEntryPoint } from './compiler/session.ts';

export const MARKER = '// @generated by slang-loader';

const HEADER = `${MARKER} — do not edit.`;

export function emitDeclaration(entryPoints: SlangEntryPoint[]): string {
  return [
    HEADER,
    '',
    'declare const code: string;',
    'export default code;',
    `export const entryPoints: ${entryPointTuple(entryPoints)};`,
    'export const reflection: unknown;',
    '',
  ].join('\n');
}

function entryPointTuple(entryPoints: SlangEntryPoint[]): string {
  if (entryPoints.length === 0) return '[]';

  const entries = entryPoints.map(entry => {
    const size = entry.workgroupSize ? `[${entry.workgroupSize.join(', ')}]` : 'null';
    return `  { name: ${JSON.stringify(entry.name)}; stage: ${JSON.stringify(entry.stage)}; workgroupSize: ${size} }`;
  });
  return `[\n${entries.join(',\n')}\n]`;
}
